import { Roboto } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto", // Create CSS Variable
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${roboto.variable} antialiased`}>{children}<ToastContainer position="top-center" autoClose={2000} /></body>
    </html>
  );
}
