import { Roboto } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import MainLayout from "@/component/layout/main-layout";
import Providers from "@/lib/providers";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto", // Create CSS Variable
});
export const metadata = {
  title: "FreshNow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${roboto.variable} antialiased`}
      >
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
        <ToastContainer position="top-center" autoClose={2000} />
      </body>
    </html>
  );
}
